### ISSUE TITLE
No class2scans.pkl

### ISSUE THREAD

**Issue by sj-li** [Na-Z/attMPTI#7]
Hi, thanks for your excellent work!

I have tried to run your code but face some issues.
After I processed the data successfully as introduction, I run :

`bash scripts/pretrain_segmentor.sh`

But ir reports:

> {0: 'ceiling', 1: 'floor', 2: 'wall', 3: 'beam', 4: 'column', 5: 'window', 6: 'door', 7: 'table', 8: 'chair', 9: 'sofa', 10: 'bookcase', 11: 'board', 12: 'clutter'}
==== class to scans mapping is done ====
         class_id: 0 | min_ratio: 0.05 | min_pts: 100 | class_name: ceiling | num of scans: 0
         class_id: 1 | min_ratio: 0.05 | min_pts: 100 | class_name: floor | num of scans: 0
         class_id: 2 | min_ratio: 0.05 | min_pts: 100 | class_name: wall | num of scans: 0
         class_id: 3 | min_ratio: 0.05 | min_pts: 100 | class_name: beam | num of scans: 0
         class_id: 4 | min_ratio: 0.05 | min_pts: 100 | class_name: column | num of scans: 0
         class_id: 5 | min_ratio: 0.05 | min_pts: 100 | class_name: window | num of scans: 0
         class_id: 6 | min_ratio: 0.05 | min_pts: 100 | class_name: door | num of scans: 0
         class_id: 7 | min_ratio: 0.05 | min_pts: 100 | class_name: table | num of scans: 0
         class_id: 8 | min_ratio: 0.05 | min_pts: 100 | class_name: chair | num of scans: 0
         class_id: 9 | min_ratio: 0.05 | min_pts: 100 | class_name: sofa | num of scans: 0
         class_id: 10 | min_ratio: 0.05 | min_pts: 100 | class_name: bookcase | num of scans: 0
         class_id: 11 | min_ratio: 0.05 | min_pts: 100 | class_name: board | num of scans: 0
         class_id: 12 | min_ratio: 0.05 | min_pts: 100 | class_name: clutter | num of scans: 0
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    pretrain(args)
  File "/media/work/li/new/Few-shot/PointSeg/attMPTI/runs/pre_train.py", line 98, in pretrain
    DATASET = S3DISDataset(args.cvfold, args.data_path)
  File "/media/work/li/new/Few-shot/PointSeg/attMPTI/dataloaders/s3dis.py", line 38, in __init__
    self.class2scans = self.get_class2scans()
  File "/media/work/li/new/Few-shot/PointSeg/attMPTI/dataloaders/s3dis.py", line 69, in get_class2scans
    with open(class2scans_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './datasets/S3DIS/blocks_bs1_s1/class2scans.pkl'

I'm not sure where is wrong. I cannot find class2scans.pkl. Thanks for your help!

**Comment by yeah334** [comment]
class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删

**Comment by WhereKey** [comment]
> Hi, thanks for your excellent work!
> 
> I have tried to run your code but face some issues.
> After I processed the data successfully as introduction, I run :
> 
> `bash scripts/pretrain_segmentor.sh`
> 
> But ir reports:
> 
> > {0: 'ceiling', 1: 'floor', 2: 'wall', 3: 'beam', 4: 'column', 5: 'window', 6: 'door', 7: 'table', 8: 'chair', 9: 'sofa', 10: 'bookcase', 11: 'board', 12: 'clutter'}
> > ==== class to scans mapping is done ====
> > class_id: 0 | min_ratio: 0.05 | min_pts: 100 | class_name: ceiling | num of scans: 0
> > class_id: 1 | min_ratio: 0.05 | min_pts: 100 | class_name: floor | num of scans: 0
> > class_id: 2 | min_ratio: 0.05 | min_pts: 100 | class_name: wall | num of scans: 0
> > class_id: 3 | min_ratio: 0.05 | min_pts: 100 | class_name: beam | num of scans: 0
> > class_id: 4 | min_ratio: 0.05 | min_pts: 100 | class_name: column | num of scans: 0
> > class_id: 5 | min_ratio: 0.05 | min_pts: 100 | class_name: window | num of scans: 0
> > class_id: 6 | min_ratio: 0.05 | min_pts: 100 | class_name: door | num of scans: 0
> > class_id: 7 | min_ratio: 0.05 | min_pts: 100 | class_name: table | num of scans: 0
> > class_id: 8 | min_ratio: 0.05 | min_pts: 100 | class_name: chair | num of scans: 0
> > class_id: 9 | min_ratio: 0.05 | min_pts: 100 | class_name: sofa | num of scans: 0
> > class_id: 10 | min_ratio: 0.05 | min_pts: 100 | class_name: bookcase | num of scans: 0
> > class_id: 11 | min_ratio: 0.05 | min_pts: 100 | class_name: board | num of scans: 0
> > class_id: 12 | min_ratio: 0.05 | min_pts: 100 | class_name: clutter | num of scans: 0
> > Traceback (most recent call last):
> > File "main.py", line 116, in 
> > pretrain(args)
> > File "/media/work/li/new/Few-shot/PointSeg/attMPTI/runs/pre_train.py", line 98, in pretrain
> > DATASET = S3DISDataset(args.cvfold, args.data_path)
> > File "/media/work/li/new/Few-shot/PointSeg/attMPTI/dataloaders/s3dis.py", line 38, in **init**
> > self.class2scans = self.get_class2scans()
> > File "/media/work/li/new/Few-shot/PointSeg/attMPTI/dataloaders/s3dis.py", line 69, in get_class2scans
> > with open(class2scans_file, 'wb') as f:
> > FileNotFoundError: [Errno 2] No such file or directory: './datasets/S3DIS/blocks_bs1_s1/class2scans.pkl'
> 
> I'm not sure where is wrong. I cannot find class2scans.pkl. Thanks for your help!

hello, how do you solve the problem?

**Comment by 964918993** [comment]
> class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删

您好，我也遇到了同样的问题。检查了dataloders/s3dis.py文件，并没有缺失代码，和作者的代码一致，还是报了相同的错误。请问您知道怎么解决吗

**Comment by 964918993** [comment]
Hi, I have the same problem. The dataloders/s3dis.py file is checked. There is no missing code, which is consistent with the author's code, and the same error is reported. Do you know how to solve it?

**Comment by WhereKey** [comment]
> > class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删
> 
> 您好，我也遇到了同样的问题。检查了dataloders/s3dis.py文件，并没有缺失代码，和作者的代码一致，还是报了相同的错误。请问您知道怎么解决吗

add '/' to the end  in pretrain_segmentor.sh  DATA_PATH='./datasets/S3DIS/blocks_bs1_s1/'   could solve the problem. But the project still will face cuda error :(

**Comment by 964918993** [comment]
> > > class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删
> > 
> > 
> > 您好，我也遇到了同样的问题。检查了dataloders/s3dis.py文件，并没有缺失代码，和作者的代码一致，还是报了相同的错误。请问您知道怎么解决吗
> 
> add '/' to the end in pretrain_segmentor.sh DATA_PATH='./datasets/S3DIS/blocks_bs1_s1/' could solve the problem. But the project still will face cuda error :(

Thank you for your help, I have successfully solved the problem. I have not encountered the CUDA problem at this time. If necessary, I can provide you with the experimental environment and a list of versions of each package.

**Comment by WhereKey** [comment]
> > > > class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删
> > > 
> > > 
> > > 您好，我也遇到了同样的问题。检查了dataloders/s3dis.py文件，并没有缺失代码，和作者的代码一致，还是报了相同的错误。请问您知道怎么解决吗
> > 
> > 
> > add '/' to the end in pretrain_segmentor.sh DATA_PATH='./datasets/S3DIS/blocks_bs1_s1/' could solve the problem. But the project still will face cuda error :(
> 
> Thank you for your help, I have successfully solved the problem. I have not encountered the CUDA problem at this time. If necessary, I can provide you with the experimental environment and a list of versions of each package.

大兄弟捞捞我，谢谢啦

**Comment by 964918993** [comment]
> > > > > class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删
> > > > 
> > > > 
> > > > 您好，我也遇到了同样的问题。检查了dataloders/s3dis.py文件，并没有缺失代码，和作者的代码一致，还是报了相同的错误。请问您知道怎么解决吗
> > > 
> > > 
> > > add '/' to the end in pretrain_segmentor.sh DATA_PATH='./datasets/S3DIS/blocks_bs1_s1/' could solve the problem. But the project still will face cuda error :(
> > 
> > 
> > Thank you for your help, I have successfully solved the problem. I have not encountered the CUDA problem at this time. If necessary, I can provide you with the experimental environment and a list of versions of each package.
> 
> 大兄弟捞捞我，谢谢啦

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0  
_tflow_select             2.1.0                       gpu  
absl-py                   0.11.0           py36h06a4308_0  
aiohttp                   3.6.3            py36h7b6447c_0  
argon2-cffi               20.1.0           py36h7b6447c_1  
asn1crypto                1.4.0                      py_0  
astor                     0.8.1                    py36_0  
astunparse                1.6.3                      py_0  
async-timeout             3.0.1                    py36_0  
async_generator           1.10             py36h28b3542_0  
attrs                     20.2.0                     py_0  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
blinker                   1.4                      py36_0  
brotlipy                  0.7.0           py36h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.16.1               h7b6447c_0  
ca-certificates           2021.7.5             h06a4308_1  
cachetools                4.1.1                      py_0  
cairo                     1.14.12              h8948797_3  
certifi                   2021.5.30        py36h06a4308_0  
cffi                      1.14.0           py36h2e261b9_0  
chardet                   3.0.4                 py36_1003  
click                     7.1.2                      py_0  
cloudpickle               1.6.0                      py_0  
cryptography              2.3.1            py36hc365091_0  
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cupti                     10.1.168                      0  
curl                      7.61.0               h84994c4_0  
cycler                    0.10.0                   py36_0  
cytoolz                   0.11.0           py36h7b6447c_0  
dask-core                 2.30.0                     py_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py36_0  
expat                     2.2.10               he6710b0_2  
faiss                     1.5.3                    pypi_0    pypi
faiss-cpu                 1.7.1           py3.6_h2a577fa_1_cpu    pytorch
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.10.4               h5ab3b9f_0  
freexl                    1.0.5                h14c3975_0  
fribidi                   1.0.10               h7b6447c_0  
gast                      0.2.2                    py36_0  
gdal                      2.2.2            py36hc209d97_1  
geos                      3.6.2                heeff764_2  
giflib                    5.1.4                h14c3975_1  
glib                      2.63.1               h5a9c865_0  
google-auth               1.23.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.2              pyhd3eb1b0_2  
google-pasta              0.2.0                      py_0  
graphite2                 1.3.14               h23475e2_0  
graphviz                  2.40.1               h21bd128_2  
grpcio                    1.14.1           py36h9ba97e2_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
h5py                      2.8.0            py36h989c5e5_3  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.2               hba1933b_1  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
idna_ssl                  1.1.0                    py36_0  
imageio                   2.9.0                      py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py36h5ca1d4c_0  
ipython                   7.16.1           py36h5ca1d4c_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.5.1                      py_1  
jasper                    2.0.14               h07fcdf6_1  
jedi                      0.17.2                   py36_0  
jinja2                    2.11.2                     py_0  
joblib                    0.17.0                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
json-c                    0.13.1               h1bed415_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py36_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py36_0  
jupyterlab_pygments       0.1.2                      py_0  
kealib                    1.4.7                h77bc034_6  
keras-applications        1.0.8                      py_1  
keras-base                2.3.1                    py36_0  
keras-gpu                 2.3.1                         0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.3.0            py36h2531618_0  
krb5                      1.16.1               hc83ff2d_6  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libboost                  1.67.0               h46d08c1_4  
libcurl                   7.61.0               h1ad7b7a_0  
libdap4                   3.19.1               h6ec2957_0  
libedit                   3.1.20191231         h14c3975_1  
libfaiss                  1.7.1            h2bc3f7f_1_cpu    pytorch
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   2.2.4                h6f639c0_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0                hf484d3e_1  
libkml                    1.3.0                h590aaf7_4  
libnetcdf                 4.6.1                h10edf3e_1  
libopencv                 3.4.2                hb342d67_1  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libpq                     10.5                 h1ad7b7a_0  
libprotobuf               3.13.0.1             hd408876_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialite             4.3.0a              he475c7f_19  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
markdown                  3.3.2                    py36_0  
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                3.3.2                         0  
matplotlib-base           3.3.2            py36h817c723_0  
mistune                   0.8.4            py36h7b6447c_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.2.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
mock                      4.0.2                      py_0  
multidict                 4.7.6            py36h7b6447c_1  
nb_conda                  2.2.1                    py36_0  
nb_conda_kernels          2.3.0                    py36_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py36_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.1                      py_0  
networkx                  2.5                        py_0  
ninja                     1.10.1           py36hfd86e86_0  
notebook                  6.1.4                    py36_0  
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
oauthlib                  3.1.0                      py_0  
olefile                   0.46                     py36_0  
opencv                    3.4.2            py36h6fd60c2_1  
opencv-contrib-python     4.4.0.44                 pypi_0    pypi
openjpeg                  2.3.0                h05c96fa_1  
openssl                   1.0.2u               h7b6447c_0  
opt_einsum                3.1.0                      py_0  
packaging                 20.4                       py_0  
pandas                    1.1.3            py36he6710b0_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.2                    py36_1  
pango                     1.42.4               h049681c_0  
parso                     0.7.0                      py_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pillow                    8.0.1            py36he98fc37_0  
pip                       20.2.4                   py36_0  
pixman                    0.40.0               h7b6447c_0  
plyfile                   0.7.2                    pypi_0    pypi
poppler                   0.65.0               h581218d_1  
poppler-data              0.4.10               h06a4308_0  
proj4                     5.0.1                h14c3975_0  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
protobuf                  3.13.0.1         py36he6710b0_1  
ptyprocess                0.6.0                    py36_0  
py-opencv                 3.4.2            py36hb342d67_1  
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.20                       py_2  
pydot                     1.4.1                    pypi_0    pypi
pygments                  2.7.2              pyhd3eb1b0_0  
pyjwt                     1.7.1                    py36_0  
pyopenssl                 19.0.0                   py36_0  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py36h05f1152_2  
pyrsistent                0.17.3           py36h7b6447c_0  
pysocks                   1.7.1                    py36_0  
python                    3.6.6                h6e4f718_2  
python-dateutil           2.8.1                      py_0  
pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py36h7b6447c_2  
pyyaml                    5.3.1            py36h7b6447c_1  
pyzmq                     19.0.2           py36he6710b0_1  
qt                        5.9.6                h8703b6f_2  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h7b6447c_5  
requests                  2.24.0                     py_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.6                        py_0  
scikit-image              0.17.2           py36hdf5156a_0  
scikit-learn              0.21.0                   pypi_0    pypi
scipy                     1.5.2            py36h0b6359f_0  
send2trash                1.5.0                    py36_0  
setuptools                50.3.0           py36hb0f4dca_1  
sip                       4.19.8           py36hf484d3e_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h62c20be_0  
tensorboard               1.14.0           py36hf484d3e_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                1.14.0          gpu_py36h3fb9ad6_0  
tensorflow-base           1.14.0          gpu_py36he45bfe2_0  
tensorflow-estimator      1.14.0                     py_0  
tensorflow-gpu            1.14.0               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
terminado                 0.9.1                    py36_0  
testpath                  0.4.4                      py_0  
tifffile                  2020.10.1        py36hdd07704_2  
tk                        8.6.10               hbc83047_0  
toolz                     0.11.1                     py_0  
toposort                  1.5                      pypi_0    pypi
torch-cluster             1.5.4                    pypi_0    pypi
torchvision               0.5.0                py36_cu101    pytorch
tornado                   6.0.4            py36h7b6447c_1  
tqdm                      4.50.2                     py_0  
traitlets                 4.3.3                    py36_0  
transforms3d              0.3.1                    pypi_0    pypi
typing_extensions         3.7.4.3                    py_0  
urllib3                   1.25.11                    py_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py36_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py36_0  
wrapt                     1.12.1           py36h7b6447c_1  
xerces-c                  3.2.3                h780794e_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.6.2            py36h7b6447c_0  
zeromq                    4.3.3                he6710b0_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0

**Comment by Chengyuelan** [comment]
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    pretrain(args)
  File "/homel/attMPTI-main/runs/pre_train.py", line 98, in pretrain
    DATASET = S3DISDataset(args.cvfold, args.data_path)
  File "/home/attMPTI-main/dataloaders/s3dis.py", line 17, in __init__
    class_names = open(os.path.join(os.path.dirname(data_path), 'meta', 's3dis_classnames.txt')).readlines()
FileNotFoundError: [Errno 2] No such file or directory: './datasets/S3DIS/blocks_bs1_s1/meta/s3dis_classnames.txt'


> > > class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删
> > 
> > 
> > 您好，我也遇到了同样的问题。检查了dataloders/s3dis.py文件，并没有缺失代码，和作者的代码一致，还是报了相同的错误。请问您知道怎么解决吗
> 
> add '/' to the end in pretrain_segmentor.sh DATA_PATH='./datasets/S3DIS/blocks_bs1_s1/' could solve the problem. 
but some problem still exist
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    pretrain(args)
  File "/home/attMPTI-main/runs/pre_train.py", line 98, in pretrain
    DATASET = S3DISDataset(args.cvfold, args.data_path)
  File "/home/attMPTI-main/dataloaders/s3dis.py", line 17, in __init__
    class_names = open(os.path.join(os.path.dirname(data_path), 'meta', 's3dis_classnames.txt')).readlines()
FileNotFoundError: [Errno 2] No such file or directory: './datasets/S3DIS/blocks_bs1_s1/meta/s3dis_classnames.txt'

**Comment by Chengyuelan** [comment]
> > > > > class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删
> > > > 
> > > > 
> > > > 您好，我也遇到了同样的问题。检查了dataloders/s3dis.py文件，并没有缺失代码，和作者的代码一致，还是报了相同的错误。请问您知道怎么解决吗
> > > 
> > > 
> > > add '/' to the end in pretrain_segmentor.sh DATA_PATH='./datasets/S3DIS/blocks_bs1_s1/' could solve the problem. But the project still will face cuda error :(
> > 
> > 
> > Thank you for your help, I have successfully solved the problem. I have not encountered the CUDA problem at this time. If necessary, I can provide you with the experimental environment and a list of versions of each package.
> 我在训练的时候遇上了这种问题，请问这个GPU的问题你解决了嘛？
usage: main.py [-h]
               [--phase {pretrain,finetune,prototrain,protoeval,mptitrain,mptieval}]
               [--dataset DATASET] [--cvfold CVFOLD] [--data_path DATA_PATH]
               [--pretrain_checkpoint_path PRETRAIN_CHECKPOINT_PATH]
               [--model_checkpoint_path MODEL_CHECKPOINT_PATH]
               [--save_path SAVE_PATH] [--eval_interval EVAL_INTERVAL]
               [--batch_size BATCH_SIZE] [--n_workers N_WORKERS]
               [--n_iters N_ITERS] [--lr LR] [--step_size STEP_SIZE]
               [--gamma GAMMA] [--pretrain_lr PRETRAIN_LR]
               [--pretrain_weight_decay PRETRAIN_WEIGHT_DECAY]
               [--pretrain_step_size PRETRAIN_STEP_SIZE]
               [--pretrain_gamma PRETRAIN_GAMMA] [--n_way N_WAY]
               [--k_shot K_SHOT] [--n_queries N_QUERIES]
               [--n_episode_test N_EPISODE_TEST] [--pc_npts PC_NPTS]
               [--pc_attribs PC_ATTRIBS] [--pc_augm]
               [--pc_augm_scale PC_AUGM_SCALE] [--pc_augm_rot PC_AUGM_ROT]
               [--pc_augm_mirror_prob PC_AUGM_MIRROR_PROB]
               [--pc_augm_jitter PC_AUGM_JITTER] [--dgcnn_k DGCNN_K]
               [--edgeconv_widths EDGECONV_WIDTHS]
               [--dgcnn_mlp_widths DGCNN_MLP_WIDTHS]
               [--base_widths BASE_WIDTHS] [--output_dim OUTPUT_DIM]
               [--use_attention] [--dist_method DIST_METHOD]
               [--n_subprototypes N_SUBPROTOTYPES] [--k_connect K_CONNECT]
               [--sigma SIGMA]
main.py: error: unrecognized arguments: --gpu_id 0 --similarity_function gaussian --output_widths [64]

**Comment by ild12** [comment]
> > > > class2scans.pkl是经pretrain_segmentor.sh处理后才生成的。with open(class2scans_file, 'wb') as f:这句之前有判断是否存在该文件的语句，可以检查一下是否误删
> > > 
> > > 
> > > 您好，我也遇到了同样的问题。检查了dataloders/s3dis.py文件，并没有缺失代码，和作者的代码一致，还是报了相同的错误。请问您知道怎么解决吗
> > 
> > 
> > add '/' to the end in pretrain_segmentor.sh DATA_PATH='./datasets/S3DIS/blocks_bs1_s1/' could solve the problem. But the project still will face cuda error :(
> 
> Thank you for your help, I have successfully solved the problem. I have not encountered the CUDA problem at this time. If necessary, I can provide you with the experimental environment and a list of versions of each package.

不，会报新的错误：[Errno 2] No such file or directory: '/datasets/S3DIS/blocks_bs1_s1/meta/s3dis_classnames.txt'这种文件目录都写不清楚，真的sm，mlgb不行就不要开源
